spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    hikari:
      maximum-pool-size: 60
      connection-timeout: 60000
      idle-timeout: 60000
      validation-timeout: 3000
      max-lifetime: 600000
      login-timeout: 5
      minimum-idle: 10
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.113.194.64:3306/student_forum_data?useUnicode=true&characterEncoding=utf-8&useSSL=true&jdbcCompliantTruncation=false&allowMultiQueries=true
    username: root
    password: AaKJ+d1~fEF4P-92Ql?cO!0kn73Bw}5q
#    url: jdbc:mysql://202.194.14.120:3306/web_2023_24?useUnicode=true&characterEncoding=utf-8&useSSL=true&jdbcCompliantTruncation=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
#    username: web_2023_24
#    password: Teachweb2023.24

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

path:
#  web-path: http://127.0.0.1:22222
  web-path: http://47.113.194.64:22222
#  web-path: http://202.194.7.29:22222

  default-avatar-name: default-avatar.png
  default-photo-name: default-photo.png

  image-web-path: /image/
#  image-local-path: D:/resource/forum/img/
  image-local-path: /home/resource/forum/img/
#  image-local-path: /teach/web/2023/attach/img/

  video-web-path: /video/
#  video-local-path: D:/resource/forum/video/
  video-local-path: /home/resource/forum/video/
#  video-local-path: /teach/web/2023/attach/video/

  audio-web-path: /audio/
#  audio-local-path: D:/resource/forum/audio/
  audio-local-path: /home/resource/forum/audio/
#  audio-local-path: /teach/web/2023/attach/audio/

page:
  page-size: 10

server:
  port: 22222
